INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (1, 1, 'Даосизм', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (2, 1, 'Индуизм', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (3, 1, 'Иудаизм', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (4, 1, 'Буддизм', true);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (5, 2, 'Часовые', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (6, 2, 'Артиллерия', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (7, 2, 'Пулеметное гнездо', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (8, 2, 'Пушка', true);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (9, 3, 'Д. И. Фонвизин', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (10, 3, 'Г. Р. Державин', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (11, 3, 'Н. М. Карамзин', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (12, 3, 'А. Н. Радищев', true);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (13, 4, 'Гафний', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (14, 4, 'Бериллий', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (15, 4, 'Теллур', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (16, 4, 'Кобальт', true);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (17, 5, 'Один', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (18, 5, 'Три', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (19, 5, 'Четыре', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (20, 5, 'Два', true);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (21, 6, 'Три', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (22, 6, 'Четыре', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (23, 6, 'Пять', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (24, 6, 'Шесть', true);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (25, 7, 'Юнг', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (26, 7, 'Гегель', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (27, 7, 'Шопенгауэр', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (28, 7, 'Ницше', true);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (29, 8, 'Кирасиры', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (30, 8, 'Уланы', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (31, 8, 'Гусары', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (32, 8, 'Драгуны', true);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (33, 9, 'Тбилиси', true);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (34, 9, 'Ереван', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (35, 9, 'Баку', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (36, 9, 'Минск', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (37, 10, 'Романист', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (38, 10, 'Драматург', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (39, 10, 'Эссеист', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (40, 10, 'Поэт', true);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (54, 13, 'Шея', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (55, 13, 'Уста', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (56, 13, 'Палец', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (57, 13, 'Спина', true);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (58, 14, 'Жнейка', true);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (59, 14, 'Шапка', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (60, 14, 'Болезнь', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (61, 14, 'Печка', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (62, 15, 'Валентин', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (63, 15, 'Евгений', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (64, 15, 'Виктор', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (67, 15, 'Георгий', true);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (68, 16, 'Висбаден', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (69, 16, 'Цербст', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (70, 16, 'Дармштадт', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (72, 16, 'Штеттин', true);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (73, 17, 'Пускать пыль в глаза', true);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (76, 17, 'Точить лясы', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (77, 17, 'Бить баклуши', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (78, 17, 'Переливать из пустого в порожнее', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (79, 18, 'Брошь', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (80, 18, 'Кольцо', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (81, 18, 'Кулон', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (82, 18, 'Браслет', true);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (83, 19, 'Опьянение', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (84, 19, 'Любовь', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (85, 19, 'Уединение', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (86, 19, 'Сон', true);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (87, 20, 'Лох чилийский', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (88, 20, 'Лох греческий', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (89, 20, 'Лох русский', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (90, 20, 'Лох индийский', true);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (91, 21, 'К Жучке', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (92, 21, 'К дочке', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (93, 21, 'к залу', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (94, 21, 'К внучке', true);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (95, 22, 'get()', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (96, 22, 'lenghtof()', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (97, 22, 'Sizeof()', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (98, 22, 'length()', true);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (99, 23, 'От -128 до 127', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (100, 23, 'От 0 до 256', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (101, 23, 'Ничего из вышеперечисленного', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (102, 23, 'От 0 до 65535', true);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (103, 24, 'Нет верного ответа', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (104, 24, 'Кофе)', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (105, 24, 'Чай)', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (106, 24, 'Язык программирования', true);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (111, 25, 'int', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (112, 25, 'long)', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (113, 25, 'double)', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (114, 25, 'char', true);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (115, 26, '0', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (116, 26, '60', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (117, 26, '25', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (118, 26, '50', true);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (119, 27, 'static', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (120, 27, 'synchronized', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (121, 27, 'strictfp', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (122, 27, 'foreign', true);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (123, 28, 'Не знаю', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (124, 28, 'Текущий экземпляр класса', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (125, 28, 'Наследованный класс', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (126, 28, 'Текущий экземпляр родительского класса', true);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (127, 29, 'Set', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (128, 29, 'Map', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (129, 29, 'System', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (130, 29, 'List', true);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (131, 30, 'Не знаю', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (132, 30, 'CY', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (133, 30, 'FIFO', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (134, 30, 'LIFO', true);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (135, 31, 'Не знаю', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (136, 31, 'Он не имеет тела', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (137, 31, 'Он не является классом', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (138, 31, 'Он объявлен как final', true);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (139, 32, 'Не знаю', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (140, 32, 'r, w, s, r+, s+, w+', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (141, 32, 'rws, rwd', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (142, 32, 'r, rw, rws, rwd', true);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (143, 33, 'Не знаю', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (144, 33, 'java.thread', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (145, 33, 'java.line', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (146, 33, 'java.io', true);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (147, 34, 'не знаю', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (148, 34, 'string.reverse();', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (149, 34, 'string.return();', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (150, 34, 'stringBuilder.reverse();', true);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (151, 35, 'не знаю', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (152, 35, 'TERMINATED', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (153, 35, 'RUNNABLE', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (154, 35, 'PAUSED', true);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (155, 36, 'не знаю', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (156, 36, 'pause()', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (157, 36, 'stop()', false);
INSERT INTO millionaire.answers (id, idquestion, answer, isrightanswer) VALUES (158, 36, 'wait()', true);
