INSERT INTO millionaire.questions (id, question) VALUES (1, 'Одним из направлений какой религиозной философии является учение дзен?');
INSERT INTO millionaire.questions (id, question) VALUES (2, 'С какой фигуры начинаются соревнования по городошному спорту');
INSERT INTO millionaire.questions (id, question) VALUES (3, 'Кто из перечисленных был пажом во времена Екатерины II');
INSERT INTO millionaire.questions (id, question) VALUES (4, 'Какой химический элемент назван в честь злого подземного гнома');
INSERT INTO millionaire.questions (id, question) VALUES (5, 'Сколько раз в сутки подзаводят куранты Спасской башни Кремля');
INSERT INTO millionaire.questions (id, question) VALUES (6, 'Сколько морей омывают Балканский полуостров');
INSERT INTO millionaire.questions (id, question) VALUES (7, 'Кто из этих философов в 1864 году написал музыку на стихи А. С. Пушкина «Заклинание» и «Зимний вечер»');
INSERT INTO millionaire.questions (id, question) VALUES (8, 'Какой вид кавалерии предназначался для боевых действий как в конном, так и в пешем строю');
INSERT INTO millionaire.questions (id, question) VALUES (9, 'В какой из этих столиц бывших союзных республик раньше других появилось метро');
INSERT INTO millionaire.questions (id, question) VALUES (10, 'Кто 1-м получил Нобелевскую премию по литературе');
INSERT INTO millionaire.questions (id, question) VALUES (13, 'Реки с каким названием нет на территории России');
INSERT INTO millionaire.questions (id, question) VALUES (14, 'Что такое лобогрейка');
INSERT INTO millionaire.questions (id, question) VALUES (15, 'Какое имя не принимал ни один папа римский');
INSERT INTO millionaire.questions (id, question) VALUES (16, 'В каком немецком городе родилась будущая императрица России Екатерина II');
INSERT INTO millionaire.questions (id, question) VALUES (17, 'Что запрещал указ, который в 1726 году подписала Екатерина I');
INSERT INTO millionaire.questions (id, question) VALUES (18, 'Какое украшение в виде змейки стало уликой в фильме "Место встречи изменить нельзя"');
INSERT INTO millionaire.questions (id, question) VALUES (19, 'Что Шекспир назвал «вкуснейшим из блюд в земном пиру»');
INSERT INTO millionaire.questions (id, question) VALUES (20, 'Какое растение существует на самом деле');
INSERT INTO millionaire.questions (id, question) VALUES (21, 'К кому первому обратились за помощью дед и бабка, не справившись с репкой');
INSERT INTO millionaire.questions (id, question) VALUES (22, 'Какой из этих методов класса String используется для получения длины объекта String?');
INSERT INTO millionaire.questions (id, question) VALUES (23, 'Что из следующего является диапазоном char в Java?');
INSERT INTO millionaire.questions (id, question) VALUES (24, 'что такое Java?');
INSERT INTO millionaire.questions (id, question) VALUES (25, 'Какой из типов относится к беззнаковым?');
INSERT INTO millionaire.questions (id, question) VALUES (26, 'Сколько ключевых слов зарезервировано языком?');
INSERT INTO millionaire.questions (id, question) VALUES (27, 'Какого модификатора класса не существует?');
INSERT INTO millionaire.questions (id, question) VALUES (28, 'Что представляет ключевое слово super?');
INSERT INTO millionaire.questions (id, question) VALUES (29, 'Vector - реализация интерфейса:');
INSERT INTO millionaire.questions (id, question) VALUES (30, 'По какому принципу работает стэк?');
INSERT INTO millionaire.questions (id, question) VALUES (31, 'Почему нельзя наследовать от класса String?');
INSERT INTO millionaire.questions (id, question) VALUES (32, 'Какие режимы открытия файла существуют в Java?');
INSERT INTO millionaire.questions (id, question) VALUES (33, 'В каком пакете сосредоточен основной функционал работы с потоками?');
INSERT INTO millionaire.questions (id, question) VALUES (34, 'Каким методом можно перевернуть строку?');
INSERT INTO millionaire.questions (id, question) VALUES (35, 'В каком состоянии не может пребывать поток?');
INSERT INTO millionaire.questions (id, question) VALUES (36, 'Какой метод переводит поток в режим ожидания?');
